# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fragile"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tnakamura"]
  s.date = "2012-06-27"
  s.description = "Ruby Pipeline Framework"
  s.email = "griefworker@gmail.com"
  s.executables = ["fragile"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Rakefile",
    "VERSION",
    "bin/fragile",
    "examples/example.rb",
    "fragile.gemspec",
    "lib/fragile.rb",
    "lib/fragile/application.rb",
    "lib/fragile/dsl.rb",
    "lib/fragile/pipeline.rb",
    "lib/fragile/pipeline_manager.rb",
    "lib/fragile/plugin/console_output.rb",
    "lib/fragile/plugin/mail_output.rb",
    "lib/fragile/plugin/map_filter.rb",
    "lib/fragile/plugin/rss_input.rb",
    "lib/fragile/plugin/select_filter.rb",
    "lib/fragile/plugin_manager.rb",
    "lib/fragile/version.rb",
    "test/dsl_test.rb",
    "test/pipeline_manager_test.rb",
    "test/pipeline_test.rb",
    "test/plugin_manager_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/tnakamura/fragile"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.16"
  s.summary = "Ruby Pipeline Framework"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

